# Generated by Django 5.0.14 on 2025-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_address_alter_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified_via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID', null=True, unique=True),
        ),
    ]
