# Generated by Django 5.0.14 on 2025-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_is_verified_via_telegram_client_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Русский'), ('uz', "O'zbekcha")], help_text='Preferred language code for bot interactions', max_length=5, null=True),
        ),
    ]
