# Generated by ChatGPT on 2025-11-03
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_client_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_moderators", to="users.admin"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="salary_per_case",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_doctors", to="users.admin"),
        ),
        migrations.AlterField(
            model_name="nurse",
            name="salary_per_day",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="nurse",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_nurses", to="users.admin"),
        ),
    ]
