# Generated by Django 5.2.7 on 2025-10-29 05:36

import django.db.models.deletion
import support_requests.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[support_requests.validators.validate_phone_number])),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('answered_by', models.ForeignKey(blank=True, help_text='Moderator who handled the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
