# Generated by Django 5.2.7 on 2025-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=None, null=True, blank=True, help_text='Purchase price for the clinic', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
