# Generated by Django 5.2.7 on 2025-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicine_original_price_alter_pet_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price for the clinic', max_digits=12, null=True),
        ),
    ]
