# Generated by Django 5.2.7 on 2025-10-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_medicine_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='anamnesis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='chest_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='general_condition',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('critical', 'Critical')], default='healthy', max_length=16),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='mucous_membrane',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='stationary_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cards', to='clinic.stationaryroom'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
