# Generated by Django 5.2.7 on 2025-10-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_medicalcard_anamnesis_medicalcard_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='room_admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='room_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
