# Generated by Django 5.2.7 on 2025-10-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_medicalcard_room_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
