# Generated by Django 5.2.7 on 2025-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='revisit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
