# Generated by Django 5.1.4 on 2025-11-04 05:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_medicalcard_revisit_date'),
        ('users', '0005_role_auto_create_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Day',
                'verbose_name_plural': 'Payment Days',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='service',
            name='price_up_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional upper bound for variable pricing', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='medical_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_tasks', to='clinic.medicalcard'),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='DoctorIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='users.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Income',
                'verbose_name_plural': 'Doctor Incomes',
            },
        ),
        migrations.CreateModel(
            name='DoctorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.doctor')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_tasks', to='clinic.medicalcard')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_tasks', to='clinic.service')),
            ],
            options={
                'verbose_name': 'Doctor Task',
                'verbose_name_plural': 'Doctor Tasks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NurseIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_reset', models.DateTimeField(blank=True, null=True)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='users.nurse')),
            ],
            options={
                'verbose_name': 'Nurse Income',
                'verbose_name_plural': 'Nurse Incomes',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.client')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='users.doctor')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MedicalCardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='clinic.medicalcard')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_links', to='clinic.service')),
            ],
            options={
                'verbose_name': 'Medical Card Service',
                'verbose_name_plural': 'Medical Card Services',
                'unique_together': {('medical_card', 'service')},
            },
        ),
    ]
