# Generated by Django 5.1.4 on 2025-11-04 11:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_paymentday_payment_amount_service_price_up_to_and_more'),
        ('users', '0005_role_auto_create_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='anamnesis',
            field=models.TextField(blank=True, null=True, verbose_name='Anamnesis'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood pressure'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Body temperature'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='chest_condition',
            field=models.TextField(blank=True, null=True, verbose_name='Chest condition'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diet',
            field=models.TextField(blank=True, null=True, verbose_name='Diet'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='general_condition',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('critical', 'Critical')], default='healthy', max_length=16, verbose_name='General condition'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Heart rate'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='medical_cards', to='clinic.medicine', verbose_name='Medicines'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mucous_membrane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mucous membrane'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory rate'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='revisit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Revisit date'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='room_admission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admission date'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='room_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='medical_cards', to='clinic.service', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='stationary_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cards', to='clinic.stationaryroom', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total fee'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(verbose_name='Expire date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price for the clinic', max_digits=12, null=True, verbose_name='Purchase price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=16, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to='users.moderator', verbose_name='Processed by'),
        ),
        migrations.AlterField(
            model_name='paymentday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='paymentday',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total for day'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_up_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional upper bound for variable pricing', max_digits=12, null=True, verbose_name='Max price'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admission date'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Occupied'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='pet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationary_room', to='clinic.pet', verbose_name='Pet'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Release date'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='room_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Room number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
    ]
