# Generated by Django 5.1.4 on 2025-11-04 12:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_medicalcard_anamnesis_and_more'),
        ('users', '0005_role_auto_create_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('reptile', 'Reptile'), ('rodent', 'Rodent'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='anamnesis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='chest_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diagnosis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='general_condition',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('critical', 'Critical')], default='healthy', max_length=16),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='medical_cards', to='clinic.medicine'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='mucous_membrane',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='revisit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='room_admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='room_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='medical_cards', to='clinic.service'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='stationary_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cards', to='clinic.stationaryroom'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price for the clinic', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to='users.moderator'),
        ),
        migrations.AlterField(
            model_name='paymentday',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='paymentday',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.client'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_up_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional upper bound for variable pricing', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='pet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationary_room', to='clinic.pet'),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationaryroom',
            name='room_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
