# Generated by Django on 2025-11-04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_alter_medicalcard_anamnesis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="animal_type",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("dog", "Dog"),
                    ("cat", "Cat"),
                    ("bird", "Bird"),
                    ("reptile", "Reptile"),
                    ("rodent", "Rodent"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
